@startuml
skinparam classAttributeIconSize 0

class Character {
- name : String
- expLevel : int
- location : String
- weaponName : String
- weaponType : WeaponType

}

class CharacterStateSave {
- nameCopy : String
- expLevelCopy : int
- locationCopy : String
- weaponNameCopy : String
- weaponTypeCopy : WeaponType
+ saves : ArrayDeque<Character>

+ save() : Character
+ restoreToSavedState(character : Character) : void
+ getSave() : Character
+ addSave() : void
+ displayFullCharacterState(character Character) : void
}

note right {
- Sets Character details using the copy values
  in CharacterStateSave.
- Does the above by creating an instance of character in save method
- Restores the character by letting copy variables equal whats in the
  character class variables.
- Adds the character state to a stack - first in, first out
- Uses GetSave to take state from the top of the stack and then 'pops'
  the stack - removes the most recently added state
}

class WeaponType {
+ ASSAULT_RIFLE : String
+ SUBMACHINE_GUN : String
+ SNIPER_RIFLE : String
+ SHOTGUN : String
+ KNIFE : String
}

class Location {
+ WHD : String
+ WHM : String
+ WRN : String
+ KL : String
+ WF : String
}

note right {
- Final String for each
  Location.
}

Character <|.. CharacterStateSave : uses

@enduml