@startuml
skinparam classAttributeIconSize 0

class CharacterState {
- name : String
- expLevel : int
- location : String
}

class CharacterStateSave {
- nameCopy : String
- expLevelCopy : int
- locationCopy : String
- weaponNameCopy : String
- weaponTypeCopy : WeaponType

+ saveState(characterState : CharacterState, weapon : Weapon)
+ restoreToSavedState(characterState : CharacterState, weapon : Weapon)
+ displayFullCharacterState(characterState CharacterState, weapon : Weapon)
}

class Weapon {
- weaponName : String
- weaponType : WeaponType
}

enum WeaponType {
ASSAULT_RIFLE
SUBMACHINE_GUN
SNIPER_RIFLE
SHOTGUN
KNIFE
}

Weapon --|> WeaponType : uses
Weapon <|-- CharacterState : uses
Weapon <|-- CharacterStateSave : uses
WeaponType <|-- CharacterStateSave : uses
CharacterState <|-- CharacterStateSave : uses


@enduml